-- ============================================================
-- CommerceOS Migration 006: the application store in Postgres (FIX_IMPLEMENTATION_PLAN FX-41, ADR-108)
--
-- Everything lives in its own schema, `commerceos`, so it never collides with the legacy tables that migrations
-- 001-005 created in `public` from a schema that had drifted from the domain types (those files are kept in
-- migrations/legacy/ and no longer run).
--
-- Every row keeps the full domain record in `data` (jsonb), exactly as the TypeScript types define it. The columns used
-- for constraints and indexes are GENERATED from `data`, so they can never disagree with the record. The writer only
-- sets id, tenant_id, created_at and data.
--
-- Core aggregates (identity, catalog and inventory, customers, orders, social inbox, automation runs) get their own
-- tables with constraints; the remaining collections are JSONB documents in `commerceos.documents` (FX-44).
--
-- Constraints that span rows are DEFERRABLE INITIALLY DEFERRED: the store writes a batch of changes in one
-- transaction, and a child row may be written before its parent within that batch. They are checked at COMMIT.
-- ============================================================

CREATE SCHEMA IF NOT EXISTS commerceos;

-- ── Single writer (replaces the .data/commerceos.lock file of FX-24) ─────────────────────────────────────────────
-- One row. The owning process renews heartbeat_at; another process may take over only after the lease has expired.
-- Every write transaction locks this row and checks the owner first (fencing).
CREATE TABLE IF NOT EXISTS commerceos.store_writer (
    id            integer     PRIMARY KEY CHECK (id = 1),
    owner         text        NOT NULL,
    host          text        NOT NULL,
    pid           integer     NOT NULL,
    started_at    timestamptz NOT NULL DEFAULT now(),
    heartbeat_at  timestamptz NOT NULL DEFAULT now()
);

-- ── Identity ─────────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS commerceos.tenants (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    slug            text GENERATED ALWAYS AS (data->>'slug') STORED,
    status          text GENERATED ALWAYS AS (data->>'status') STORED,
    CONSTRAINT tenants_tenant_is_self CHECK (tenant_id = id),
    CONSTRAINT tenants_slug_key UNIQUE (slug) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS commerceos.users (
    id              text        PRIMARY KEY,
    tenant_id       text,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    email_key       text GENERATED ALWAYS AS (lower(btrim(data->>'email'))) STORED,
    status          text GENERATED ALWAYS AS (data->>'status') STORED,
    CONSTRAINT users_email_key UNIQUE (email_key) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS commerceos.memberships (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    user_id         text GENERATED ALWAYS AS (data->>'user_id') STORED,
    role            text GENERATED ALWAYS AS (data->>'role') STORED,
    CONSTRAINT memberships_tenant_user_key UNIQUE (tenant_id, user_id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT memberships_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES commerceos.tenants (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT memberships_user_fkey FOREIGN KEY (user_id) REFERENCES commerceos.users (id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS memberships_user_idx ON commerceos.memberships (user_id);

CREATE TABLE IF NOT EXISTS commerceos.invitations (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    email_key       text GENERATED ALWAYS AS (lower(btrim(data->>'email'))) STORED,
    status          text GENERATED ALWAYS AS (data->>'status') STORED
);
CREATE INDEX IF NOT EXISTS invitations_tenant_status_idx ON commerceos.invitations (tenant_id, status);

CREATE TABLE IF NOT EXISTS commerceos.audit_logs (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    action          text GENERATED ALWAYS AS (data->>'action') STORED,
    resource_type   text GENERATED ALWAYS AS (data->>'resource_type') STORED,
    resource_id     text GENERATED ALWAYS AS (data->>'resource_id') STORED
);
CREATE INDEX IF NOT EXISTS audit_logs_tenant_created_idx ON commerceos.audit_logs (tenant_id, created_at DESC);

CREATE TABLE IF NOT EXISTS commerceos.service_tokens (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    key_hash        text GENERATED ALWAYS AS (data->>'key_hash') STORED,
    CONSTRAINT service_tokens_key_hash_key UNIQUE (key_hash) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS commerceos.platform_memberships (
    id              text        PRIMARY KEY,
    tenant_id       text,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    user_id         text GENERATED ALWAYS AS (data->>'user_id') STORED,
    role            text GENERATED ALWAYS AS (data->>'role') STORED
);
CREATE INDEX IF NOT EXISTS platform_memberships_user_idx ON commerceos.platform_memberships (user_id);

CREATE TABLE IF NOT EXISTS commerceos.impersonation_sessions (
    id              text        PRIMARY KEY,
    tenant_id       text,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    status          text GENERATED ALWAYS AS (data->>'status') STORED
);

-- ── Catalog and inventory ────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS commerceos.products (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    sku_key         text GENERATED ALWAYS AS (upper(data->>'sku')) STORED,
    status          text GENERATED ALWAYS AS (data->>'status') STORED,
    category_id     text GENERATED ALWAYS AS (data->>'category_id') STORED,
    CONSTRAINT products_tenant_id_key UNIQUE (tenant_id, id),
    -- SKUs are unique per workspace, case-insensitively, as ProductService.createProduct enforces.
    CONSTRAINT products_tenant_sku_key UNIQUE (tenant_id, sku_key) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS products_tenant_status_idx ON commerceos.products (tenant_id, status);

CREATE TABLE IF NOT EXISTS commerceos.product_variants (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    product_id      text GENERATED ALWAYS AS (data->>'product_id') STORED,
    sku_key         text GENERATED ALWAYS AS (upper(data->>'sku')) STORED,
    CONSTRAINT product_variants_tenant_id_key UNIQUE (tenant_id, id),
    CONSTRAINT product_variants_product_fkey FOREIGN KEY (tenant_id, product_id)
        REFERENCES commerceos.products (tenant_id, id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS product_variants_product_idx ON commerceos.product_variants (tenant_id, product_id);
CREATE INDEX IF NOT EXISTS product_variants_sku_idx ON commerceos.product_variants (tenant_id, sku_key);

CREATE TABLE IF NOT EXISTS commerceos.categories (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    slug            text GENERATED ALWAYS AS (data->>'slug') STORED
);
CREATE INDEX IF NOT EXISTS categories_tenant_slug_idx ON commerceos.categories (tenant_id, slug);

CREATE TABLE IF NOT EXISTS commerceos.brands (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    slug            text GENERATED ALWAYS AS (data->>'slug') STORED
);
CREATE INDEX IF NOT EXISTS brands_tenant_slug_idx ON commerceos.brands (tenant_id, slug);

CREATE TABLE IF NOT EXISTS commerceos.warehouses (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    code            text GENERATED ALWAYS AS (data->>'code') STORED,
    CONSTRAINT warehouses_tenant_id_key UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS commerceos.inventory_items (
    id                  text        PRIMARY KEY,
    tenant_id           text        NOT NULL,
    seq                 bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at          timestamptz,
    row_updated_at      timestamptz NOT NULL DEFAULT now(),
    data                jsonb       NOT NULL,
    warehouse_id        text    GENERATED ALWAYS AS (data->>'warehouse_id') STORED,
    product_variant_id  text    GENERATED ALWAYS AS (data->>'product_variant_id') STORED,
    quantity_on_hand    numeric GENERATED ALWAYS AS ((data->>'quantity_on_hand')::numeric) STORED,
    quantity_reserved   numeric GENERATED ALWAYS AS ((data->>'quantity_reserved')::numeric) STORED,
    -- On-hand stock may go below zero only when a workspace allows overselling (tenant setting), so only the reserved
    -- quantity is constrained here (ADR-108, deviation from FX-41).
    CONSTRAINT inventory_items_reserved_nonnegative CHECK (quantity_reserved >= 0),
    CONSTRAINT inventory_items_location_key UNIQUE (tenant_id, warehouse_id, product_variant_id) DEFERRABLE INITIALLY DEFERRED,
    -- Stock can only sit in the workspace's own warehouse (the M11 bug class, FX-36).
    CONSTRAINT inventory_items_warehouse_fkey FOREIGN KEY (tenant_id, warehouse_id)
        REFERENCES commerceos.warehouses (tenant_id, id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT inventory_items_variant_fkey FOREIGN KEY (tenant_id, product_variant_id)
        REFERENCES commerceos.product_variants (tenant_id, id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS commerceos.stock_movements (
    id                  text        PRIMARY KEY,
    tenant_id           text        NOT NULL,
    seq                 bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at          timestamptz,
    row_updated_at      timestamptz NOT NULL DEFAULT now(),
    data                jsonb       NOT NULL,
    product_variant_id  text GENERATED ALWAYS AS (data->>'product_variant_id') STORED,
    reference_id        text GENERATED ALWAYS AS (data->>'reference_id') STORED
);
CREATE INDEX IF NOT EXISTS stock_movements_variant_idx ON commerceos.stock_movements (tenant_id, product_variant_id, created_at DESC);

CREATE TABLE IF NOT EXISTS commerceos.inventory_reservations (
    id                  text        PRIMARY KEY,
    tenant_id           text        NOT NULL,
    seq                 bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at          timestamptz,
    row_updated_at      timestamptz NOT NULL DEFAULT now(),
    data                jsonb       NOT NULL,
    order_id            text    GENERATED ALWAYS AS (data->>'order_id') STORED,
    status              text    GENERATED ALWAYS AS (data->>'status') STORED,
    quantity            numeric GENERATED ALWAYS AS ((data->>'quantity')::numeric) STORED,
    CONSTRAINT inventory_reservations_quantity_positive CHECK (quantity > 0)
);
CREATE INDEX IF NOT EXISTS inventory_reservations_order_idx ON commerceos.inventory_reservations (tenant_id, order_id);
CREATE INDEX IF NOT EXISTS inventory_reservations_status_idx ON commerceos.inventory_reservations (tenant_id, status);

-- ── Customers ────────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS commerceos.customers (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    phone           text GENERATED ALWAYS AS (data->>'phone') STORED,
    email_key       text GENERATED ALWAYS AS (lower(btrim(data->>'email'))) STORED,
    status          text GENERATED ALWAYS AS (data->>'status') STORED,
    CONSTRAINT customers_tenant_id_key UNIQUE (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS customers_tenant_phone_idx ON commerceos.customers (tenant_id, phone);
CREATE INDEX IF NOT EXISTS customers_tenant_created_idx ON commerceos.customers (tenant_id, created_at DESC);

CREATE TABLE IF NOT EXISTS commerceos.customer_addresses (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    customer_id     text GENERATED ALWAYS AS (data->>'customer_id') STORED,
    CONSTRAINT customer_addresses_customer_fkey FOREIGN KEY (tenant_id, customer_id)
        REFERENCES commerceos.customers (tenant_id, id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS customer_addresses_customer_idx ON commerceos.customer_addresses (tenant_id, customer_id);

-- ── Orders, payments, fulfilment ─────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS commerceos.orders (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    order_number    text    GENERATED ALWAYS AS (data->>'order_number') STORED,
    status          text    GENERATED ALWAYS AS (data->>'status') STORED,
    payment_status  text    GENERATED ALWAYS AS (data->>'payment_status') STORED,
    customer_id     text    GENERATED ALWAYS AS (data->>'customer_id') STORED,
    grand_total     numeric GENERATED ALWAYS AS ((data->>'grand_total')::numeric) STORED,
    CONSTRAINT orders_tenant_id_key UNIQUE (tenant_id, id),
    CONSTRAINT orders_tenant_order_number_key UNIQUE (tenant_id, order_number) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS orders_tenant_created_idx ON commerceos.orders (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS orders_tenant_status_idx ON commerceos.orders (tenant_id, status);
CREATE INDEX IF NOT EXISTS orders_tenant_customer_idx ON commerceos.orders (tenant_id, customer_id);

-- Last order number issued per workspace (FX-35); a later round increments it in SQL inside the order transaction.
CREATE TABLE IF NOT EXISTS commerceos.order_sequences (
    tenant_id       text        PRIMARY KEY,
    value           bigint      NOT NULL CHECK (value >= 0),
    row_updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS commerceos.order_items (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    order_id        text    GENERATED ALWAYS AS (data->>'order_id') STORED,
    variant_id      text    GENERATED ALWAYS AS (data->>'variant_id') STORED,
    quantity        numeric GENERATED ALWAYS AS ((data->>'quantity')::numeric) STORED,
    CONSTRAINT order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT order_items_order_fkey FOREIGN KEY (tenant_id, order_id)
        REFERENCES commerceos.orders (tenant_id, id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS order_items_order_idx ON commerceos.order_items (tenant_id, order_id);

CREATE TABLE IF NOT EXISTS commerceos.payments (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    order_id        text    GENERATED ALWAYS AS (data->>'order_id') STORED,
    provider        text    GENERATED ALWAYS AS (data->>'provider') STORED,
    status          text    GENERATED ALWAYS AS (data->>'status') STORED,
    amount          numeric GENERATED ALWAYS AS ((data->>'amount')::numeric) STORED,
    -- Compared trimmed and case-insensitively, as PaymentService does; NULL (no transaction id) never collides.
    transaction_key text    GENERATED ALWAYS AS (nullif(upper(btrim(data->>'transaction_id')), '')) STORED,
    CONSTRAINT payments_transaction_key UNIQUE (tenant_id, provider, transaction_key) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT payments_order_fkey FOREIGN KEY (tenant_id, order_id)
        REFERENCES commerceos.orders (tenant_id, id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS payments_order_idx ON commerceos.payments (tenant_id, order_id);
CREATE INDEX IF NOT EXISTS payments_tenant_created_idx ON commerceos.payments (tenant_id, created_at DESC);

CREATE TABLE IF NOT EXISTS commerceos.shipments (
    id               text        PRIMARY KEY,
    tenant_id        text        NOT NULL,
    seq              bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at       timestamptz,
    row_updated_at   timestamptz NOT NULL DEFAULT now(),
    data             jsonb       NOT NULL,
    order_id         text GENERATED ALWAYS AS (data->>'order_id') STORED,
    status           text GENERATED ALWAYS AS (data->>'status') STORED,
    courier_provider text GENERATED ALWAYS AS (data->>'courier_provider') STORED,
    tracking_number  text GENERATED ALWAYS AS (data->>'tracking_number') STORED,
    CONSTRAINT shipments_order_fkey FOREIGN KEY (tenant_id, order_id)
        REFERENCES commerceos.orders (tenant_id, id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS shipments_order_idx ON commerceos.shipments (tenant_id, order_id);
CREATE INDEX IF NOT EXISTS shipments_tenant_status_idx ON commerceos.shipments (tenant_id, status);
CREATE INDEX IF NOT EXISTS shipments_tracking_idx ON commerceos.shipments (courier_provider, tracking_number);

CREATE TABLE IF NOT EXISTS commerceos.returns (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    order_id        text GENERATED ALWAYS AS (data->>'order_id') STORED,
    status          text GENERATED ALWAYS AS (data->>'status') STORED,
    CONSTRAINT returns_order_fkey FOREIGN KEY (tenant_id, order_id)
        REFERENCES commerceos.orders (tenant_id, id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS returns_order_idx ON commerceos.returns (tenant_id, order_id);

CREATE TABLE IF NOT EXISTS commerceos.refunds (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    order_id        text    GENERATED ALWAYS AS (data->>'order_id') STORED,
    payment_id      text    GENERATED ALWAYS AS (data->>'payment_id') STORED,
    amount          numeric GENERATED ALWAYS AS ((data->>'amount')::numeric) STORED,
    CONSTRAINT refunds_order_fkey FOREIGN KEY (tenant_id, order_id)
        REFERENCES commerceos.orders (tenant_id, id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS refunds_order_idx ON commerceos.refunds (tenant_id, order_id);

CREATE TABLE IF NOT EXISTS commerceos.coupons (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    code            text GENERATED ALWAYS AS (data->>'code') STORED,
    CONSTRAINT coupons_tenant_code_key UNIQUE (tenant_id, code) DEFERRABLE INITIALLY DEFERRED
);

-- Commerce domain events (append-only log).
CREATE TABLE IF NOT EXISTS commerceos.events (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    type            text GENERATED ALWAYS AS (data->>'type') STORED,
    aggregate_id    text GENERATED ALWAYS AS (data->>'aggregate_id') STORED
);
CREATE INDEX IF NOT EXISTS events_tenant_created_idx ON commerceos.events (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS events_aggregate_idx ON commerceos.events (tenant_id, aggregate_id);

-- ── Social inbox ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS commerceos.connected_channels (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    type            text GENERATED ALWAYS AS (data->>'type') STORED,
    status          text GENERATED ALWAYS AS (data->>'status') STORED
);

CREATE TABLE IF NOT EXISTS commerceos.customer_identities (
    id               text        PRIMARY KEY,
    tenant_id        text        NOT NULL,
    seq              bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at       timestamptz,
    row_updated_at   timestamptz NOT NULL DEFAULT now(),
    data             jsonb       NOT NULL,
    customer_id      text GENERATED ALWAYS AS (data->>'customer_id') STORED,
    channel_type     text GENERATED ALWAYS AS (data->>'channel_type') STORED,
    external_user_id text GENERATED ALWAYS AS (data->>'external_user_id') STORED
);
CREATE INDEX IF NOT EXISTS customer_identities_external_idx ON commerceos.customer_identities (tenant_id, channel_type, external_user_id);
CREATE INDEX IF NOT EXISTS customer_identities_customer_idx ON commerceos.customer_identities (tenant_id, customer_id);

CREATE TABLE IF NOT EXISTS commerceos.conversations (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    customer_id     text GENERATED ALWAYS AS (data->>'customer_id') STORED,
    channel_id      text GENERATED ALWAYS AS (data->>'channel_id') STORED,
    status          text GENERATED ALWAYS AS (data->>'status') STORED,
    CONSTRAINT conversations_tenant_id_key UNIQUE (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS conversations_tenant_status_idx ON commerceos.conversations (tenant_id, status);
CREATE INDEX IF NOT EXISTS conversations_tenant_customer_idx ON commerceos.conversations (tenant_id, customer_id);

CREATE TABLE IF NOT EXISTS commerceos.messages (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    conversation_id     text GENERATED ALWAYS AS (data->>'conversation_id') STORED,
    external_message_id text GENERATED ALWAYS AS (data->>'external_message_id') STORED,
    CONSTRAINT messages_conversation_fkey FOREIGN KEY (tenant_id, conversation_id)
        REFERENCES commerceos.conversations (tenant_id, id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS messages_conversation_idx ON commerceos.messages (tenant_id, conversation_id, created_at);
CREATE INDEX IF NOT EXISTS messages_external_idx ON commerceos.messages (tenant_id, external_message_id);

CREATE TABLE IF NOT EXISTS commerceos.leads (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    customer_id     text GENERATED ALWAYS AS (data->>'customer_id') STORED,
    status          text GENERATED ALWAYS AS (data->>'status') STORED
);
CREATE INDEX IF NOT EXISTS leads_tenant_customer_idx ON commerceos.leads (tenant_id, customer_id);

-- ── Automation ───────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS commerceos.automation_workflows (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    status          text GENERATED ALWAYS AS (data->>'status') STORED
);

CREATE TABLE IF NOT EXISTS commerceos.automation_executions (
    id              text        PRIMARY KEY,
    tenant_id       text        NOT NULL,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    automation_id   text GENERATED ALWAYS AS (data->>'automation_id') STORED,
    status          text GENERATED ALWAYS AS (data->>'status') STORED
);
CREATE INDEX IF NOT EXISTS automation_executions_tenant_created_idx ON commerceos.automation_executions (tenant_id, created_at DESC);

-- ── Every other collection: JSONB documents (FX-44) ──────────────────────────────────────────────────────────────
-- Growth, intelligence, operations, enterprise, autonomous, AI and platform-configuration collections are low-write
-- and document-shaped. tenant_id is NULL for platform-scope documents.
CREATE TABLE IF NOT EXISTS commerceos.documents (
    collection      text        NOT NULL,
    id              text        NOT NULL,
    tenant_id       text,
    seq             bigint      GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamptz,
    row_updated_at  timestamptz NOT NULL DEFAULT now(),
    data            jsonb       NOT NULL,
    PRIMARY KEY (collection, id)
);
CREATE INDEX IF NOT EXISTS documents_tenant_idx ON commerceos.documents (tenant_id, collection, row_updated_at DESC);
CREATE INDEX IF NOT EXISTS documents_collection_seq_idx ON commerceos.documents (collection, seq);

-- Records Postgres refused (a constraint, a malformed value), kept here in the same transaction so they survive a
-- restart and stay reported until they are saved or an operator resolves them. `data` is NULL for a refused delete.
CREATE TABLE IF NOT EXISTS commerceos.refused_rows (
    collection      text        NOT NULL,
    id              text        NOT NULL,
    tenant_id       text,
    op              text        NOT NULL CHECK (op IN ('upsert', 'delete')),
    reason          text        NOT NULL,
    constraint_name text,
    data            jsonb,
    refused_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (collection, id)
);

-- Store-level values that are not collections of records.
CREATE TABLE IF NOT EXISTS commerceos.store_meta (
    key             text        PRIMARY KEY,
    value           jsonb       NOT NULL,
    row_updated_at  timestamptz NOT NULL DEFAULT now()
);
