/**
 * Production readiness R1: /health/ready reports Qdrant, Redis and the LLM provider (READY_REQUIRED), the core scope
 * ignores them, probes are cached, and request ids are always generated by the server.
 * No request leaves this machine: probes use the stubbed outbound transport.
 * Run: node tests/ts-runner.cjs ./tests/dependency-health-tests.ts
 */
import assert from "assert";
import fs from "fs";
import path from "path";
import { db } from "@/infrastructure/db";
import { checkDependencies, failingDependencyReason, requiredDependencies, resetDependencyHealthForTesting } from "@/lib/dependency-health";
import { setOutboundLookupForTesting, setOutboundTransportForTesting } from "@/lib/outbound-http";

let passed = 0;
let failed = 0;
async function runTest(name: string, fn: () => Promise<void> | void): Promise<void> {
  try {
    await fn();
    passed++;
    console.log(`  \x1b[32m✓ PASS\x1b[0m - ${name}`);
  } catch (err) {
    failed++;
    console.log(`  \x1b[31m✗ FAIL\x1b[0m - ${name}\n      ${(err as Error).message}`);
  }
}

const ENV = {
  QDRANT_URL: "https://qdrant.example.test",
  QDRANT_API_KEY: "q-key",
  UPSTASH_REDIS_REST_URL: "https://redis.example.test",
  UPSTASH_REDIS_REST_TOKEN: "r-token",
  LLM_BASE_URL: "https://llm.example.test/v1",
  LLM_API_KEY: "l-key",
} as unknown as NodeJS.ProcessEnv;

function stub(handler: (url: URL) => number | "throw", seen: string[] = []) {
  setOutboundLookupForTesting(async () => [{ address: "93.184.216.34", family: 4 }]);
  setOutboundTransportForTesting(async (url) => {
    seen.push(url.host);
    const r = handler(url);
    if (r === "throw") throw new Error("connection refused");
    return { status: r, headers: {}, body: "{}", truncated: false, durationMs: 1 };
  });
}

async function main(): Promise<void> {
  console.log("\n[R1] readiness of external dependencies");
  await runTest("all up: every configured service is ok and required by default", async () => {
    resetDependencyHealthForTesting();
    stub(() => 200);
    const deps = await checkDependencies(ENV);
    assert.deepStrictEqual(Object.values(deps).map((d) => d.state), ["ok", "ok", "ok"]);
    assert.ok(Object.values(deps).every((d) => d.required));
    assert.strictEqual(failingDependencyReason(deps), null);
  });

  await runTest("a required service that is down gives a reason code; the response carries no URL or error text", async () => {
    resetDependencyHealthForTesting();
    stub((u) => (u.host.startsWith("qdrant") ? "throw" : 200));
    const deps = await checkDependencies(ENV);
    assert.strictEqual(deps.qdrant.state, "down");
    assert.strictEqual(failingDependencyReason(deps), "QDRANT_UNREACHABLE");
    assert.ok(!JSON.stringify(deps).includes("example.test") && !JSON.stringify(deps).includes("refused"));
  });

  await runTest("READY_REQUIRED narrows the set; a down service outside it is reported but doesn't fail readiness", async () => {
    resetDependencyHealthForTesting();
    stub((u) => (u.host.startsWith("redis") ? 500 : 200));
    const env = { ...ENV, READY_REQUIRED: "qdrant, llm" } as NodeJS.ProcessEnv;
    assert.deepStrictEqual([...requiredDependencies(env)].sort(), ["llm", "qdrant"]);
    const deps = await checkDependencies(env);
    assert.strictEqual(deps.redis.state, "down");
    assert.strictEqual(deps.redis.required, false);
    assert.strictEqual(failingDependencyReason(deps), null);
    assert.strictEqual(requiredDependencies({ READY_REQUIRED: "" } as NodeJS.ProcessEnv).size, 0);
  });

  await runTest("unconfigured services are skipped (not down) and are never contacted", async () => {
    resetDependencyHealthForTesting();
    const seen: string[] = [];
    stub(() => 200, seen);
    const deps = await checkDependencies({} as NodeJS.ProcessEnv);
    assert.deepStrictEqual(Object.values(deps).map((d) => d.state), ["not_configured", "not_configured", "not_configured"]);
    assert.deepStrictEqual(seen, []);
    assert.strictEqual(failingDependencyReason(deps), null);
  });

  await runTest("the LLM probe: 404 on /models is up (no such endpoint), 401 and 5xx are down", async () => {
    for (const [status, expected] of [[404, "ok"], [401, "down"], [503, "down"]] as const) {
      resetDependencyHealthForTesting();
      stub((u) => (u.host.startsWith("llm") ? status : 200));
      assert.strictEqual((await checkDependencies(ENV)).llm.state, expected, `status ${status}`);
    }
  });

  await runTest("probes are cached and concurrent callers share one probe (the endpoint is unauthenticated)", async () => {
    resetDependencyHealthForTesting();
    const seen: string[] = [];
    stub(() => 200, seen);
    await Promise.all([checkDependencies(ENV), checkDependencies(ENV), checkDependencies(ENV)]);
    await checkDependencies(ENV);
    assert.strictEqual(seen.length, 3, "one probe per service");
  });

  await runTest("GET /health/ready: 503 with a reason when a required service is down; ?scope=core ignores it", async () => {
    const { GET } = await import("@/app/health/ready/route");
    // A fresh checkout (CI) has no data directory yet, and readiness would answer DATA_DIR_NOT_WRITABLE before anything else
    fs.mkdirSync(db.getPersistenceHealth().data_dir, { recursive: true });
    const saved = { ...process.env };
    try {
      Object.assign(process.env, ENV);
      delete process.env.READY_REQUIRED;
      resetDependencyHealthForTesting();
      stub((u) => (u.host.startsWith("llm") ? 503 : 200));
      const full = await GET(new Request("http://localhost/health/ready"));
      const fullBody = (await full.json()) as { status: string; reason: string | null; checks: { dependencies?: Record<string, { state: string }> } };
      assert.strictEqual(full.status, 503);
      assert.strictEqual(fullBody.status, "not_ready");
      assert.strictEqual(fullBody.reason, "LLM_UNREACHABLE");
      assert.strictEqual(fullBody.checks.dependencies?.llm.state, "down");
      const core = await GET(new Request("http://localhost/health/ready?scope=core"));
      const coreBody = (await core.json()) as { status: string; checks: { dependencies?: unknown } };
      assert.strictEqual(core.status, 200);
      assert.strictEqual(coreBody.status, "ready");
      assert.strictEqual(coreBody.checks.dependencies, undefined);
    } finally {
      for (const k of Object.keys(ENV)) {
        if (saved[k] === undefined) delete process.env[k];
        else process.env[k] = saved[k];
      }
      if (saved.READY_REQUIRED !== undefined) process.env.READY_REQUIRED = saved.READY_REQUIRED;
    }
  });

  await runTest("request ids come from the server: the context extractors never read a client x-request-id", () => {
    const src = fs.readFileSync(path.join(process.cwd(), "src/lib/api-response.ts"), "utf8");
    assert.ok(!/headers.get("x-request-id")/.test(src));
  });

  setOutboundTransportForTesting(null);
  setOutboundLookupForTesting(null);
  console.log(`\n  DEPENDENCY HEALTH TEST SUMMARY: ${passed} PASSED, ${failed} FAILED`);
  process.exit(failed > 0 ? 1 : 0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
