/**
 * CommerceOS Phase 6: 39 Standard E-Commerce Automation Workflows Catalog
 * Definitive specifications for the standard templates across 8 categories:
 * Orders, Payments, Inventory, Shipping, Customers, Social/Leads, Marketing, Finance/Operations.
 */

import { StandardWorkflowTemplate } from "@/types/automation";

export const STANDARD_WORKFLOW_TEMPLATES: StandardWorkflowTemplate[] = [
  // ============================================================
  // CATEGORY A: ORDER AUTOMATION (01 - 05)
  // ============================================================
  {
    id: "tmpl_ord_01",
    code: "WF-ORD-01",
    name: "New Order Notification",
    category: "ORDER",
    description: "Validates incoming order.created event, notifies store operators via SMS/WhatsApp, and dispatches customer confirmation.",
    trigger_type: "EVENT",
    trigger_event: "order.created",
    required_permissions: ["orders.read", "automation.execute"],
    required_integrations: ["CommerceOS API", "SMS Gateway"],
    configuration_schema: {
      operator_phone: "string",
      notify_channels: ["sms", "whatsapp", "in_app"],
      include_order_breakdown: true,
    },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["SMS", "WhatsApp", "In-App"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-order-created-notification.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_ord_02",
    code: "WF-ORD-02",
    name: "Order Confirmation Automation",
    category: "ORDER",
    description: "Sends customer confirmation notice and internal fulfillment signal when order is marked CONFIRMED.",
    trigger_type: "EVENT",
    trigger_event: "order.confirmed",
    required_permissions: ["orders.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { send_pdf_invoice: false, notify_warehouse: true },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["SMS", "WhatsApp", "Email"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-order-confirmation.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_ord_03",
    code: "WF-ORD-03",
    name: "Order Cancellation Automation",
    category: "ORDER",
    description: "Executes stock release request, notifies customer and customer support team upon order cancellation.",
    trigger_type: "EVENT",
    trigger_event: "order.cancelled",
    required_permissions: ["orders.read", "inventory.adjust", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { auto_release_stock: true, notify_customer: true },
    risk_level: "MEDIUM",
    approval_requirement: "NONE",
    supported_channels: ["SMS", "WhatsApp", "In-App"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-order-cancellation.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_ord_04",
    code: "WF-ORD-04",
    name: "Pending Order Reminder",
    category: "ORDER",
    description: "Periodically identifies orders pending confirmation for over 12 hours and alerts merchant operators.",
    trigger_type: "SCHEDULE",
    cron_schedule: "0 */4 * * *",
    required_permissions: ["orders.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { pending_hours_threshold: 12, alert_limit: 50 },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "SMS"],
    retry_policy: { max_attempts: 2, initial_delay_ms: 2000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-pending-order-reminder.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_ord_05",
    code: "WF-ORD-05",
    name: "High-Value Order Alert",
    category: "ORDER",
    description: "Evaluates order total against high-value threshold and creates operator review task before fulfillment dispatch.",
    trigger_type: "EVENT",
    trigger_event: "order.created",
    required_permissions: ["orders.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { value_threshold_bdt: 10000, require_verification_call: true },
    risk_level: "MEDIUM",
    approval_requirement: "RECOMMENDED",
    supported_channels: ["In-App", "SMS", "WhatsApp"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["manager_alert"] },
    n8n_workflow_file: "commerceos-high-value-order-alert.json",
    version: "1.0.0",
  },

  // ============================================================
  // CATEGORY B: PAYMENT AUTOMATION (06 - 10)
  // ============================================================
  {
    id: "tmpl_pay_01",
    code: "WF-PAY-01",
    name: "Payment Success Notification",
    category: "PAYMENT",
    description: "Dispatches customer receipt and emits fulfillment signal when payment.completed occurs via bKash, Nagad, or Card.",
    trigger_type: "EVENT",
    trigger_event: "payment.completed",
    required_permissions: ["payments.read", "automation.execute"],
    required_integrations: ["CommerceOS API", "bKash / Nagad API"],
    configuration_schema: { send_sms_receipt: true, auto_trigger_fulfillment: true },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["SMS", "WhatsApp", "In-App"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-payment-verification.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_pay_02",
    code: "WF-PAY-02",
    name: "Payment Failure Recovery",
    category: "PAYMENT",
    description: "Detects failed MFS/card payment, notifies customer with alternative payment link and retries if provider permits.",
    trigger_type: "EVENT",
    trigger_event: "payment.failed",
    required_permissions: ["payments.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { include_alternative_link: true, grace_period_hours: 24 },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["SMS", "WhatsApp"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-payment-failure-recovery.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_pay_03",
    code: "WF-PAY-03",
    name: "Pending Payment Reminder",
    category: "PAYMENT",
    description: "Queries unpaid digital payment orders older than 2 hours and sends polite payment link nudge.",
    trigger_type: "SCHEDULE",
    cron_schedule: "0 */2 * * *",
    required_permissions: ["payments.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { wait_hours_before_nudge: 2, max_nudges: 2 },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["SMS", "WhatsApp"],
    retry_policy: { max_attempts: 2, initial_delay_ms: 2000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-pending-payment-reminder.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_pay_04",
    code: "WF-PAY-04",
    name: "COD Confirmation Workflow",
    category: "PAYMENT",
    description: "Dispatches automated verification request for Cash On Delivery orders and escalates unconfirmed orders.",
    trigger_type: "EVENT",
    trigger_event: "order.created",
    required_permissions: ["orders.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { channel: "whatsapp", timeout_hours: 6 },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["WhatsApp", "SMS"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-cod-confirmation.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_pay_05",
    code: "WF-PAY-05",
    name: "Refund Completion Notification",
    category: "PAYMENT",
    description: "Notifies customer upon refund completion and records ledger execution in communication log.",
    trigger_type: "EVENT",
    trigger_event: "refund.completed",
    required_permissions: ["payments.refund", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { notify_customer: true, include_trx_id: true },
    risk_level: "MEDIUM",
    approval_requirement: "NONE",
    supported_channels: ["SMS", "Email", "In-App"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["finance_alert"] },
    n8n_workflow_file: "commerceos-refund-completion.json",
    version: "1.0.0",
  },

  // ============================================================
  // CATEGORY C: INVENTORY AUTOMATION (11 - 15)
  // ============================================================
  {
    id: "tmpl_inv_01",
    code: "WF-INV-01",
    name: "Low Stock Alert",
    category: "INVENTORY",
    description: "Monitors inventory threshold breaches, alerts warehouse manager, and generates replenishment task draft.",
    trigger_type: "EVENT",
    trigger_event: "inventory.low_stock",
    required_permissions: ["inventory.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { alert_slack_webhook: false, notify_warehouse_manager: true },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "SMS", "Email"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["warehouse_alert"] },
    n8n_workflow_file: "commerceos-inventory-low-stock-alert.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_inv_02",
    code: "WF-INV-02",
    name: "Out-of-Stock Alert",
    category: "INVENTORY",
    description: "Alerts catalog operations upon stock depletion and halts active promotions for the affected SKU.",
    trigger_type: "EVENT",
    trigger_event: "inventory.out_of_stock",
    required_permissions: ["inventory.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { notify_social_channels: true, pause_ads: false },
    risk_level: "MEDIUM",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "SMS"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["inventory_alert"] },
    n8n_workflow_file: "commerceos-out-of-stock-alert.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_inv_03",
    code: "WF-INV-03",
    name: "Inventory Replenishment Request",
    category: "INVENTORY",
    description: "Calculates reorder quantity using velocity models and generates a purchase requisition for manager sign-off.",
    trigger_type: "EVENT",
    trigger_event: "inventory.low_stock",
    required_permissions: ["inventory.adjust", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { default_lead_time_days: 7, require_manager_approval: true },
    risk_level: "HIGH",
    approval_requirement: "MANDATORY",
    supported_channels: ["In-App", "Email"],
    retry_policy: { max_attempts: 2, initial_delay_ms: 2000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["procurement_alert"] },
    n8n_workflow_file: "commerceos-inventory-replenishment.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_inv_04",
    code: "WF-INV-04",
    name: "Inventory Transfer Notification",
    category: "INVENTORY",
    description: "Notifies destination warehouse and logistics coordinator when stock transfer between hubs is initiated.",
    trigger_type: "EVENT",
    trigger_event: "inventory.transfer",
    required_permissions: ["inventory.transfer", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { notify_receiving_hub: true },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "SMS"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["warehouse_alert"] },
    n8n_workflow_file: "commerceos-inventory-transfer.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_inv_05",
    code: "WF-INV-05",
    name: "Inventory Adjustment Alert",
    category: "INVENTORY",
    description: "Audits manual stock adjustments, flags variances exceeding threshold, and alerts operations leadership.",
    trigger_type: "EVENT",
    trigger_event: "inventory.adjusted",
    required_permissions: ["inventory.adjust", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { variance_quantity_threshold: 10 },
    risk_level: "MEDIUM",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "Email"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["audit_alert"] },
    n8n_workflow_file: "commerceos-inventory-adjustment-alert.json",
    version: "1.0.0",
  },

  // ============================================================
  // CATEGORY D: SHIPPING & COURIER (16 - 22)
  // ============================================================
  {
    id: "tmpl_del_01",
    code: "WF-DEL-01",
    name: "Shipment Creation Automation",
    category: "SHIPPING",
    description: "Validates recipient address and requests consignment creation through CommerceOS with Steadfast or Pathao.",
    trigger_type: "EVENT",
    trigger_event: "order.ready_to_ship",
    required_permissions: ["shipments.create", "automation.execute"],
    required_integrations: ["CommerceOS API", "Steadfast / Pathao API"],
    configuration_schema: { preferred_courier: "STEADFAST", auto_print_waybill: false },
    risk_level: "MEDIUM",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "Courier API"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1500, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["dispatch_alert"] },
    n8n_workflow_file: "commerceos-courier-consignment-creation.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_del_02",
    code: "WF-DEL-02",
    name: "Courier Pickup Notification",
    category: "SHIPPING",
    description: "Sends customer notification with tracking ID once consignment is verified as picked up by courier rider.",
    trigger_type: "EVENT",
    trigger_event: "shipment.picked_up",
    required_permissions: ["shipments.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { channel: "sms", include_tracking_url: true },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["SMS", "WhatsApp"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-courier-pickup-notification.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_del_03",
    code: "WF-DEL-03",
    name: "In-Transit Notification",
    category: "SHIPPING",
    description: "Pushes status update and tracking link to customer as package traverses courier sorting hubs.",
    trigger_type: "EVENT",
    trigger_event: "shipment.in_transit",
    required_permissions: ["shipments.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { notify_customer: true },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["WhatsApp", "SMS"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-in-transit-notification.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_del_04",
    code: "WF-DEL-04",
    name: "Out-for-Delivery Notification",
    category: "SHIPPING",
    description: "Sends urgent morning reminder to customer with expected delivery window and exact COD amount due.",
    trigger_type: "EVENT",
    trigger_event: "shipment.out_for_delivery",
    required_permissions: ["shipments.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { mention_cod_amount: true, send_rider_phone: false },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["SMS", "WhatsApp"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-out-for-delivery-notification.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_del_05",
    code: "WF-DEL-05",
    name: "Delivery Confirmation",
    category: "SHIPPING",
    description: "Marks shipment DELIVERED, synchronizes COD payments, and schedules post-delivery satisfaction survey.",
    trigger_type: "EVENT",
    trigger_event: "shipment.delivered",
    required_permissions: ["shipments.update", "orders.update", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { auto_settle_cod: true, schedule_feedback_days: 3 },
    risk_level: "MEDIUM",
    approval_requirement: "NONE",
    supported_channels: ["SMS", "WhatsApp", "In-App"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-delivery-confirmation.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_del_06",
    code: "WF-DEL-06",
    name: "Delivery Failure Recovery",
    category: "SHIPPING",
    description: "Catches failed delivery attempts, logs exception, alerts support team, and contacts customer for alternate delivery instructions.",
    trigger_type: "EVENT",
    trigger_event: "shipment.failed",
    required_permissions: ["shipments.update", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { auto_retry_delivery: false, alert_support_agent: true },
    risk_level: "MEDIUM",
    approval_requirement: "NONE",
    supported_channels: ["WhatsApp", "SMS", "In-App"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["support_alert"] },
    n8n_workflow_file: "commerceos-delivery-failure-recovery.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_del_07",
    code: "WF-DEL-07",
    name: "Courier Return Synchronization",
    category: "SHIPPING",
    description: "Synchronizes return-to-origin (RTO) statuses, creates return ticket, and prepares inventory restocking checklist.",
    trigger_type: "EVENT",
    trigger_event: "shipment.returned",
    required_permissions: ["shipments.update", "returns.manage", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { create_return_ticket: true, notify_customer: true },
    risk_level: "MEDIUM",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "SMS"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["returns_alert"] },
    n8n_workflow_file: "commerceos-courier-return-synchronization.json",
    version: "1.0.0",
  },

  // ============================================================
  // CATEGORY E: CUSTOMER AUTOMATION (23 - 27)
  // ============================================================
  {
    id: "tmpl_cus_01",
    code: "WF-CUS-01",
    name: "New Customer Welcome",
    category: "CUSTOMER",
    description: "Sends personalized onboarding message and channel opt-in confirmation upon customer profile creation.",
    trigger_type: "EVENT",
    trigger_event: "customer.created",
    required_permissions: ["customers.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { welcome_discount_coupon: "WELCOME10", channel: "whatsapp" },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["WhatsApp", "SMS", "Email"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["marketing_alert"] },
    n8n_workflow_file: "commerceos-customer-welcome.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_cus_02",
    code: "WF-CUS-02",
    name: "Customer Birthday Automation",
    category: "CUSTOMER",
    description: "Identifies customers celebrating birthdays today, verifies communication consent, and dispatches celebratory discount.",
    trigger_type: "SCHEDULE",
    cron_schedule: "0 9 * * *",
    required_permissions: ["customers.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { birthday_coupon_code: "BDAY20", channel: "sms" },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["SMS", "WhatsApp"],
    retry_policy: { max_attempts: 2, initial_delay_ms: 2000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["marketing_alert"] },
    n8n_workflow_file: "commerceos-customer-birthday.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_cus_03",
    code: "WF-CUS-03",
    name: "Inactive Customer Reminder",
    category: "CUSTOMER",
    description: "Finds dormant buyers (no purchases in 60+ days) and applies frequency-capped re-engagement promotion.",
    trigger_type: "SCHEDULE",
    cron_schedule: "0 11 * * 1",
    required_permissions: ["customers.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { inactivity_days: 60, frequency_cap_days: 30 },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["WhatsApp", "SMS"],
    retry_policy: { max_attempts: 2, initial_delay_ms: 2000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["marketing_alert"] },
    n8n_workflow_file: "commerceos-inactive-customer-reminder.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_cus_04",
    code: "WF-CUS-04",
    name: "Customer Support Escalation",
    category: "CUSTOMER",
    description: "Routes urgent support queries or negative sentiment interactions to on-duty escalation agents.",
    trigger_type: "EVENT",
    trigger_event: "support.escalation",
    required_permissions: ["support.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { auto_assign_role: "MANAGER", sla_response_minutes: 15 },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "SMS"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["support_lead_alert"] },
    n8n_workflow_file: "commerceos-support-escalation.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_cus_05",
    code: "WF-CUS-05",
    name: "Customer Feedback Request",
    category: "CUSTOMER",
    description: "Waits 3 days following verified delivery scan and dispatches rating / review request link.",
    trigger_type: "EVENT",
    trigger_event: "shipment.delivered",
    required_permissions: ["customers.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { delay_days: 3, incentive_points: 50 },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["WhatsApp", "SMS"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["operator_alert"] },
    n8n_workflow_file: "commerceos-feedback-request.json",
    version: "1.0.0",
  },

  // ============================================================
  // CATEGORY F: SOCIAL / LEAD AUTOMATION (28 - 30)
  // ============================================================
  {
    id: "tmpl_soc_01",
    code: "WF-SOC-01",
    name: "New Social Lead Capture",
    category: "SOCIAL",
    description: "Resolves cross-channel customer identity from Facebook/Instagram/WhatsApp interactions and creates qualified lead.",
    trigger_type: "EVENT",
    trigger_event: "social.lead.created",
    required_permissions: ["social.lead.create", "automation.execute"],
    required_integrations: ["CommerceOS API", "Meta Graph API"],
    configuration_schema: { default_lead_score: 50, assign_to_sales_team: true },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "Meta"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["sales_alert"] },
    n8n_workflow_file: "commerceos-social-lead-capture.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_soc_02",
    code: "WF-SOC-02",
    name: "Social Inquiry Routing",
    category: "SOCIAL",
    description: "Classifies incoming chat messages (inquiry vs complaint vs order intent) and routes to specialized queue.",
    trigger_type: "EVENT",
    trigger_event: "social.message.received",
    required_permissions: ["social.message.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { enable_ai_intent_detection: true, route_banglish: true },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "WhatsApp", "Meta"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["support_alert"] },
    n8n_workflow_file: "commerceos-social-inquiry-routing.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_soc_03",
    code: "WF-SOC-03",
    name: "Social Order Follow-up",
    category: "SOCIAL",
    description: "Follows up on conversational checkout orders initiated via WhatsApp/Messenger if payment remains unconfirmed.",
    trigger_type: "EVENT",
    trigger_event: "social.order.created",
    required_permissions: ["orders.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { timeout_hours: 4, send_payment_link: true },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["WhatsApp", "Meta"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["sales_alert"] },
    n8n_workflow_file: "commerceos-social-order-followup.json",
    version: "1.0.0",
  },

  // ============================================================
  // CATEGORY G: MARKETING AUTOMATION (31 - 34)
  // ============================================================
  {
    id: "tmpl_mkt_01",
    code: "WF-MKT-01",
    name: "Abandoned Checkout Recovery",
    category: "MARKETING",
    description: "Validates customer consent, checks frequency caps, and sends WhatsApp reminder with 1-click cart restoration link.",
    trigger_type: "EVENT",
    trigger_event: "checkout.abandoned",
    required_permissions: ["marketing.read", "automation.execute"],
    required_integrations: ["CommerceOS API", "WhatsApp Business API"],
    configuration_schema: { wait_minutes: 60, discount_code: "CART5", max_reminders: 2 },
    risk_level: "MEDIUM",
    approval_requirement: "NONE",
    supported_channels: ["WhatsApp", "SMS"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["marketing_alert"] },
    n8n_workflow_file: "commerceos-abandoned-checkout-recovery.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_mkt_02",
    code: "WF-MKT-02",
    name: "Win-Back Campaign Trigger",
    category: "MARKETING",
    description: "Targets AT_RISK or DORMANT customer cohorts with curated discount offers to incentivize reactivation.",
    trigger_type: "EVENT",
    trigger_event: "customer.lifecycle.changed",
    required_permissions: ["marketing.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { target_stages: ["AT_RISK", "DORMANT"], incentive_tier: "TIER_2" },
    risk_level: "MEDIUM",
    approval_requirement: "RECOMMENDED",
    supported_channels: ["SMS", "WhatsApp", "Email"],
    retry_policy: { max_attempts: 2, initial_delay_ms: 2000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["growth_alert"] },
    n8n_workflow_file: "commerceos-winback-campaign.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_mkt_03",
    code: "WF-MKT-03",
    name: "Cross-Sell Recommendation Trigger",
    category: "MARKETING",
    description: "Generates complementary product recommendations post-delivery based on order item categories.",
    trigger_type: "EVENT",
    trigger_event: "shipment.delivered",
    required_permissions: ["marketing.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { delay_days: 7, max_items: 3 },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["WhatsApp", "Email"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["marketing_alert"] },
    n8n_workflow_file: "commerceos-cross-sell-recommendation.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_mkt_04",
    code: "WF-MKT-04",
    name: "Campaign Performance Alert",
    category: "MARKETING",
    description: "Monitors active campaign conversion and ROI thresholds, flagging underperforming broadcasts to marketers.",
    trigger_type: "SCHEDULE",
    cron_schedule: "0 18 * * *",
    required_permissions: ["marketing.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { min_conversion_rate: 0.02, min_roas: 3.0 },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "Email"],
    retry_policy: { max_attempts: 2, initial_delay_ms: 2000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["growth_alert"] },
    n8n_workflow_file: "commerceos-campaign-performance-alert.json",
    version: "1.0.0",
  },

  // ============================================================
  // CATEGORY H: FINANCE & OPERATIONS (35 - 39)
  // ============================================================
  {
    id: "tmpl_ops_01",
    code: "WF-OPS-01",
    name: "Daily Commerce Summary",
    category: "FINANCE_OPERATIONS",
    description: "Aggregates daily sales, COD collection, and pending fulfillment statistics into executive digest at 9:00 AM.",
    trigger_type: "SCHEDULE",
    cron_schedule: "0 9 * * *",
    required_permissions: ["finance.read", "orders.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { recipient_emails: ["admin@commerceos.com"], include_charts: true },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["Email", "In-App", "WhatsApp"],
    retry_policy: { max_attempts: 2, initial_delay_ms: 2000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["ops_alert"] },
    n8n_workflow_file: "commerceos-daily-commerce-summary.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_ops_02",
    code: "WF-OPS-02",
    name: "Daily Exception Summary",
    category: "FINANCE_OPERATIONS",
    description: "Compiles failed shipments, payment discrepancies, out-of-stock items, and return requests into a unified task list.",
    trigger_type: "SCHEDULE",
    cron_schedule: "30 9 * * *",
    required_permissions: ["finance.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { include_delayed_shipments: true, include_low_stock: true },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "Email"],
    retry_policy: { max_attempts: 2, initial_delay_ms: 2000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["ops_alert"] },
    n8n_workflow_file: "commerceos-daily-exception-summary.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_ops_03",
    code: "WF-OPS-03",
    name: "Daily Reconciliation Trigger",
    category: "FINANCE_OPERATIONS",
    description: "Initiates automated cross-referencing between courier remittance reports and internal COD ledger entries.",
    trigger_type: "SCHEDULE",
    cron_schedule: "0 23 * * *",
    required_permissions: ["finance.read", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { auto_reconcile_exact_matches: true, discrepancy_tolerance_bdt: 0 },
    risk_level: "HIGH",
    approval_requirement: "MANDATORY",
    supported_channels: ["In-App", "Email"],
    retry_policy: { max_attempts: 2, initial_delay_ms: 3000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["finance_alert"] },
    n8n_workflow_file: "commerceos-reconciliation-trigger.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_ops_04",
    code: "WF-OPS-04",
    name: "Provider Health Alert",
    category: "FINANCE_OPERATIONS",
    description: "Monitors courier and payment gateway error rates; trips circuit breaker and alerts managers upon degradation.",
    trigger_type: "EVENT",
    trigger_event: "provider.health_degraded",
    required_permissions: ["automation.manage_credentials", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { trip_circuit_breaker: true, notify_tech_lead: true },
    risk_level: "HIGH",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "SMS", "Email"],
    retry_policy: { max_attempts: 3, initial_delay_ms: 1000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["devops_alert"] },
    n8n_workflow_file: "commerceos-provider-health-alert.json",
    version: "1.0.0",
  },
  {
    id: "tmpl_ops_05",
    code: "WF-OPS-05",
    name: "Automation Failure Digest",
    category: "FINANCE_OPERATIONS",
    description: "Daily automated report summarizing dead-lettered jobs, retry exhaustion rates, and workflow execution latency.",
    trigger_type: "SCHEDULE",
    cron_schedule: "0 8 * * *",
    required_permissions: ["automation.view_logs", "automation.execute"],
    required_integrations: ["CommerceOS API"],
    configuration_schema: { include_stack_trace_refs: true, recipient: "ops@commerceos.com" },
    risk_level: "LOW",
    approval_requirement: "NONE",
    supported_channels: ["In-App", "Email"],
    retry_policy: { max_attempts: 2, initial_delay_ms: 2000, backoff_multiplier: 2 },
    failure_policy: { alert_channels: ["devops_alert"] },
    n8n_workflow_file: "commerceos-automation-failure-digest.json",
    version: "1.0.0",
  },
];
